# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c0c88be6ff0777fdee69e1ac52bfeff5b79e02e1c3e1821965857bd7c332b80384822ccda9b47b92fb24fc419f6e2d587cf6faff72e4d9a1e67291841f49e75

test:
  secret_key_base: 4ee0af1498a0bc4aff20d1f7cb63badcc246c88d68852d97beee6940559758bb3573bfed95273ad20dfb10c52d60b5b5a577f3fbe7e0bca53952a18a0bfa6a9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
